### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by MasterChief220** [PinkDev1/PimEyes-Crack-UserStyle#2]
The link can noway be found and the pictures are blurred too. Any fixes?

**Comment by Angellus2018** [comment]
Tried on Chrome and Mozilla
Tried both sets of instructions
Neither worked for me either

**Comment by PinkDev1** [comment]
The crack is working as expected. Quoting directly from within the "limitations" section:

> In recent updates, they made it so everything but the face is blurred. You'll have to crop the face, and reverse image search that and hope to get the original picture. This crack will still help you download that blurred image though.
> The result URLs are obfuscated and cropped to 30 characters. Although this crack will un-blur, un-hide, and make these URLs selectable, we can't recover the original content of these URLs. It's up to you if you'll be able to get back the original URL by recognizing the domain/cdn format.

If you do have any idea as to how to bypass this, Pull Requests are welcome. However, from my observations, the content is modified before being delivered to the browser, so (AFAIK) there's no way to get the original resources.

**Comment by MasterChief220** [comment]
> The crack is working as expected. Quoting directly from within the "limitations" section:
> 
> > In recent updates, they made it so everything but the face is blurred. You'll have to crop the face, and reverse image search that and hope to get the original picture. This crack will still help you download that blurred image though.
> > The result URLs are obfuscated and cropped to 30 characters. Although this crack will un-blur, un-hide, and make these URLs selectable, we can't recover the original content of these URLs. It's up to you if you'll be able to get back the original URL by recognizing the domain/cdn format.
> 
> If you do have any idea as to how to bypass this, Pull Requests are more than welcome. However, from my observations, the content is modified before being delivered to the browser, so (AFAIK) there's no way to get the original resources.

I've come across numerous premium pim eyes apks for phone however they all give me an unknown search error so I cant search any image. Maybe you should check them for pointers?

**Comment by PinkDev1** [comment]
@MasterChief220 uh, are you sure about those? It seems at some point, PimEyes made an Android app, that lasted (at least) until 2018-02-08. I know this because APKPure has a [release on their site](https://apkpure.com/pimeyes-face-finder/com.pimeyes.mobile), and APKPure is pretty much a mirror of the gplaystore. 

Anyhow, at some point the app was pulled from the playstore, and so was support for it. The inner workings of the API changed, hence why the apps throw `an unknown search error`. Nice try though `¯\_(ツ)_/¯`

**Comment by MasterChief220** [comment]
> @MasterChief220 uh, are you sure about those? It seems at some point, PimEyes made an Android app, that lasted (at least) until 2018-02-08. I know this because APKPure has a [release on their site](https://apkpure.com/pimeyes-face-finder/com.pimeyes.mobile), and APKPure is pretty much a mirror of the gplaystore.
> 
> Anyhow, at some point the app was pulled from the playstore, and so was support for it. The inner workings of the API changed, hence why the apps throw `an unknown search error`. Nice try though `¯\_(ツ)_/¯`

well was worth a try...xD. Isn't there any other reliable free search engine that looks for faces like pimeyes does?
