### ISSUE TITLE
This is not working anymore.

### ISSUE THREAD

**Issue by Rainmaker9999** [PinkDev1/PimEyes-Crack-UserStyle#4]
This is not working anymore. I think they changed their search URL. Kindly check.

**Comment by SyKoYoshi** [comment]
Can confirm, it also no longer works.

**Comment by robertheadley** [comment]
Even if you update the url where the script is active, it no longer works with the most recent update which occurred a few days ago. I know that search-by-images stopped working about three days ago. I use Pimeyes on a mostly daily basis. 

The search URL is now https://pimeyes.com/en

**Comment by PinkDev1** [comment]
Got it. I'll see what I can do.

**Comment by PinkDev1** [comment]
Fixed! :)
