### ISSUE TITLE
Request for a WebExtension

### ISSUE THREAD

**Issue by robertheadley** [PinkDev1/PimEyes-Crack-UserStyle#5]
I actually have a subscription to Pimeyes, but even with a subscription, they only really show you part of the URL for the image. You don't see the whole thing. Even then, that is not the actual URL that you are linking to, but just where the image is being hotlinked from.

It would be really nice to be able to export image results as Image Url, Link URL, and Image to a CSV or something.
I realize that this is a pretty absurd request considering the scope. But I figured I would ask.

**Comment by robertheadley** [comment]
Either way. Thank you very much for your work.

**Comment by PinkDev1** [comment]
I wouldn't really have any issue with developing this; For a while, I did think about making this crack into a browser add-on, but I didn't really know what features to add. It was also way easier to maintain a CSS stylesheet.
In a couple of weeks, I'll create a variant of this project called "PimEyes-Crack-Advanced" or something like that.

> Link URL

Are you refering to the "result" URL?

> Image

I could base64 encode it and save it in a CSV, yes.

**Comment by robertheadley** [comment]
So, normally, pimeyes shows this as the URL
![image](https://user-images.githubusercontent.com/1780455/121977621-03ce6a80-cd4c-11eb-88d5-ce6915f27b1a.png)
and then when you actually go to the site. The URL of the site is https://screenrant.com/tag/Psychonauts-2/ which doesn't have any relationship to the image. Of course in this case, the image is hosted on a CDA, but the URL of the website and the URL of the image are often different.

**Comment by PinkDev1** [comment]
Just wanted to let you know that I am actively working on this.

**Comment by robertheadley** [comment]
Awesome.

**Comment by PinkDev1** [comment]
I struggle a bit with with the asynchronous aspect of javascript. If anyone who's reading this wants to pick-up the project, I'll happily hand-over the code (WIP) that I've made.

**Comment by robertheadley** [comment]
I am not a programmer, but what I am, is a sourcer, I can generally find any kind of resource needed, libraries, example code, etc. I just can't program myself. :(

**Comment by gngenius02** [comment]
> I struggle a bit with with the asynchronous aspect of javascript. If anyone who's reading this wants to pick-up the project, I'll happily hand-over the code (WIP) that I've made.

Hey, I'd be willing to help out with this, at least try to. If this is still needed feel free to reach out.

**Comment by PinkDev1** [comment]
@gngenius02  Alright, here's the code I've made so far:
https://mega.nz/file/0hZQHLBT#8f2dd_j8cv7H0IUZDJaGG_DbBN6Eb229sOhQjtc0A1Q

Lots of parts were ripped from one of my other projects (PinkDev1/Amino-Enhancement-Suite), like the Icons.
For now, It has an improvised GUI with only the 1st button "working" (WIP). The base64 encoded SVG result-images are logged to the console, but I didn't finish the CSV generation and download.

Good luck! 😅

**Comment by maciej1988** [comment]
Thank you for your update :)

**Comment by huesos2000** [comment]
Hi there! I'm terribly sorry to ask this since I'm a complete rookie but when I try to upload this new extension from mega to my Chrome it wouldn't let me. The error it gives i can roughly translate from Russian as "Localization is used, but manifest does not include default_locale". What am I doing wrong? Thanks!

**Comment by shukumeiteki** [comment]
> @gngenius02 Alright, here's the code I've made so far: https://mega.nz/file/0hZQHLBT#8f2dd_j8cv7H0IUZDJaGG_DbBN6Eb229sOhQjtc0A1Q
> 
> Lots of parts were ripped from [one of my other projects](https://github.com/PinkDev1/Amino-Enhancement-Suite) (like the Icons) so I could start writing the code of the actual webextension as fast as possible :p For now, It has an improvised GUI with only the 1st button "working" (WIP). The base64 encoded SVG result-images are logged to the console, but I didn't finish the CSV generation and download.
> 
> Good luck! 😅

anyway you can give any help installing that add-on on firefox? since this is not a .xpi or .jar it doesnt let me install it manually :( i have no idea how to install it otherwise (i did search for a bit but no luck so far)

**Comment by huesos2000** [comment]
and the dream is gone... (look at the website)

**Comment by shukumeiteki** [comment]
well, they put everything behind a big paywall, it's also extremely slow no to do any search, it takes a min to search 1 photo, before it was a few seconds at best, so bad.

**Comment by robertheadley** [comment]
Does anyone besides me subscribe to Pimeyes?

**Comment by shukumeiteki** [comment]
For how expensive and limited this service is, I would guess so, this is clearly not aimed to individuals but rather companies or if you really need to like one time search for something really specific... I doubt anyone is willing to pay something this absurd for basically porn/curiosity/entertainment.

**Comment by robertheadley** [comment]
The site is definitely not targeted at individuals. I agree. I am disappointed that they changed the paid search from matching up to 5 photos to only 3. They also limited the number of daily searches a while back. It isn't a number I am really even close to hitting, but it is the principal. 

The nature of technology is that eventually, someone else will do what Pimeyes is doing, and if not, it will be because society decided it wasn't something that should be done.

**Comment by shukumeiteki** [comment]
As you stated correctly since they are the only ones providing this type of service they charge whatever the hell they want, basic supply and demand law.
I guess sooner or later we will see an alternative, remember this is fairly new and the boom of this site began in 2020, you just need to give it a bit of time.

**Comment by robertheadley** [comment]
I am going to try to learn how to hack away at javascript I think. It would be much easier to just interpret the API json results than to scrape any kind of Div element. Maybe the existing stuff is already doing that. 

Not sure.

**Comment by Pakwer** [comment]
Hey there, any updates on this project?

**Comment by PinkDev1** [comment]
Update: I've checked the bypass that I used to have and they've patched that too. I guess this is the end of the road for this project. I _could_ attempt to remove the fake loading bar that appears when searching results, but I don't think it's worth it.

As a word of thought, to the people at Pimeyes: I would totally have taken a 100$ bribe to shut this all down. You didn't need to change your entire business model lol

I will now be closing this issue, and archiving the repository.

# 🏴‍☠️**It has been a pleasure sailing with y'all** 🏴‍☠️
