### ISSUE TITLE
Request about a problem

### ISSUE THREAD

**Issue by Drakzorg** [PinkDev1/PimEyes-Crack-UserStyle#7]
Hi! I have a problem, the thing is, when I go to greasyfork and click in "Install as user style" (I have the stylus chrome add-on), it just redirects me to a site that looks like this (I'll insert a screenshot) 
![Screenshot_2223](https://user-images.githubusercontent.com/87040601/124660200-46332500-de7c-11eb-83d5-38b6d026cc04.png)
I tried copying that text in the stylus "Add a new style" option but I really couldn't figure out how to make it work.
I'd be glad if you can help me with this.
Thank you so much! :D

**Comment by PinkDev1** [comment]
That's odd. Try the 3rd method:

- Install the the Stylus Add-on (Chrome Version here)
- Download this repo
- Stylus -> "Manage" -> (on the left down corner) "Import"
- Select the userstyle-import.json file you downloaded.

Also, what versions of Chrome and Stylus do you have? Are you on Windows or *NIX? 
1st method works fine for me on Win10, Chrome v91.0.4472.77, Stylus v1.5.17

**Comment by Drakzorg** [comment]
Well, I'm an idiot, I didn't have stylus, I had stylish lol. After that stupid mistake, I installed stylus, and added the crack, I think it's running, but I can't make it work in the web
![Screenshot_2230](https://user-images.githubusercontent.com/87040601/124768003-ad99b500-df0e-11eb-93a1-eb4070531c2a.png)
![Screenshot_2231](https://user-images.githubusercontent.com/87040601/124768012-af637880-df0e-11eb-9768-42baa6d644a3.png)

**Comment by PinkDev1** [comment]
From the screenshots you sent, I see it's working as intented. Please read the 2nd paragraph on the README.
