### ISSUE TITLE
Not able to get URL

### ISSUE THREAD

**Issue by DJChamp** [PinkDev1/PimEyes-Crack-UserStyle#8]
![image](https://user-images.githubusercontent.com/38243591/132696322-3f3052e1-5de8-4f0b-90dc-b2e978d4f78c.png)
I am still not able to get any useful info using this.. can you please help me out

**Comment by PinkDev1** [comment]
Sorry, this crack is not able to get the full URL for free. For more info refer to the Limitations section on the Readme.
